Repository Lv-630-TAQC-Java-project/codewars630java, pull requests merged in 2021-09, with the labels that each got.

#45 #44 miles per gallon to kilometers per liter
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/EightImpl.java
Labels: 8 kyu

#36 implemented method liters #35
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/EightImpl.java
Labels: 8 kyu

#43 #42 volume of cuboid
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/EightImpl.java
Labels: 8 kyu

#40 vDmytriv_VolumeOfaCuboid
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/EightImpl.java
Labels: 8 kyu

#32 Kostyra/to-square-or-not-to-square
  src/main/java/com/ss/ita/kata/implementation/Percifalll/EightImpl.java
Labels: 8 kyu

#31 Kostyra/mpg-to-kpl
  src/main/java/com/ss/ita/kata/implementation/Percifalll/EightImpl.java
Labels: 8 kyu

#29 Kostyra/volume of a cuboid
  src/main/java/com/ss/ita/kata/implementation/Percifalll/EightImpl.java
Labels: 8 kyu

#28 Kostyra/keep hydrated
  src/main/java/com/ss/ita/kata/implementation/Percifalll/EightImpl.java
  src/main/java/com/ss/ita/kata/implementation/Percifalll/SixImpl.java
Labels: 8 kyu

#39 vDmytriv_Keep_Hydrated
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/EightImpl.java
Labels: 8 kyu

#50 ToSquareOrNotToSquare
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/EightImpl.java
Labels: 8 kyu

#52 Count/Sum
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/EightImpl.java
Labels: 8 kyu

#53 ConvertToaNumber
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/EightImpl.java
Labels: 8 kyu

#54 comlplete task to square(root) or not to square(root)
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/EightImpl.java
Labels: 8 kyu

#56 Formatting decimal places
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/EightImpl.java
Labels: 8 kyu

#59 complete task Count_of_positives_/_sum_of_negatives
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/EightImpl.java
Labels: 8 kyu

#62 complete task Convert a String to a Number
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/EightImpl.java
Labels: 8 kyu

#63 newAverage
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/SevenImpl.java
Labels: 7 kyu

#65 complete task twodecimalPlaces
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/EightImpl.java
Labels: 8 kyu

#67 Kostrya/convert-string-to-a-number
  src/main/java/com/ss/ita/kata/implementation/Percifalll/EightImpl.java
Labels: 8 kyu

#68 Kostyra/count-of-positive-sum-of-negative
  src/main/java/com/ss/ita/kata/implementation/Percifalll/EightImpl.java
Labels: 8 kyu

#69 sumOfTheFirst
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/SevenImpl.java
Labels: 7 kyu

#228 completed task Help the Bookseller
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/Six.java
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/SixImpl.java
Labels: 6 kyu

#226 225 convert a string to a number! vg
  src/main/java/com/ss/ita/kata/implementation/VladGranat/EightImpl.java
  src/main/java/com/ss/ita/kata/implementation/VladGranat/SixImpl.java
Labels: 8 kyu

#218 Closes #214 Which x for that sum?
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/FiveImpl.java
Labels: 5 kyu

#216 Closes #213 Perimeter of squares in a rectangle
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/FiveImpl.java
Labels: 5 kyu

#208 completed task Artificial Rain
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/FiveImpl.java
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/SixImpl.java
Labels: 5 kyu

#206 completed task Perimeter of squares in a rectangle
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/FiveImpl.java
Labels: 5 kyu

#204 Floating
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/Six.java
Labels: 6 kyu

#202 Smallest
  src/main/java/com/ss/ita/kata/implementation/NyxLex/FiveImpl.java
Labels: 5 kyu

#200 Perimeter in a rectangle
  src/main/java/com/ss/ita/kata/implementation/NyxLex/FiveImpl.java
Labels: 5 kyu

#199 Trailing zeros in factorial
  src/main/java/com/ss/ita/kata/implementation/NyxLex/FiveImpl.java
Labels: 5 kyu

#197 Artificial Rain
  src/main/java/com/ss/ita/kata/implementation/NyxLex/FiveImpl.java
Labels: 5 kyu

#196 complete task which x for that sum
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/FiveImpl.java
Labels: 5 kyu

#190 xForTheSum
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/FiveImpl.java
Labels: 5 kyu

#189 Kostyra/which-x-for-that-sum
  src/main/java/com/ss/ita/kata/implementation/Percifalll/FiveImpl.java
Labels: 5 kyu

#191 inPrime
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/FiveImpl.java
Labels: 5 kyu

#188 Dzhyv/perimeter of squares in a rectangle
  .gitignore
  src/main/java/com/ss/ita/kata/implementation/dzhyv/FiveImpl.java
  src/main/java/com/ss/ita/kata/implementation/dzhyv/Siximpl.java
Labels: 5 kyu

#184 Dzhyv/build a pile of cubes
  .gitignore
  src/main/java/com/ss/ita/kata/implementation/dzhyv/Siximpl.java
Labels: 6 kyu

#182 Dzhyv/rainfall
  src/main/java/com/ss/ita/kata/implementation/dzhyv/Siximpl.java
Labels: 6 kyu

#176 Dzhyv/help the bookseller!
  src/main/java/com/ss/ita/kata/implementation/dzhyv/Siximpl.java
Labels: 6 kyu

#234 hot fix
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/FiveImpl.java
  src/main/java/com/ss/ita/kata/implementation/NyxLex/FiveImpl.java
Labels: bug

#232 completed task find the smallest
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/FiveImpl.java
Labels: 5 kyu

#230 dzhyv/Floating-point_Approximation
  src/main/java/com/ss/ita/kata/implementation/dzhyv/Siximpl.java
Labels: 6 kyu

#172 PerimiterOfSquares
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/FiveImpl.java
Labels: 5 kyu

#171 Closes #154 Where is Vasya?
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/SevenImpl.java
Labels: 7 kyu

#170 Closes #153 Sum of the first nth term of Series
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/SevenImpl.java
Labels: 7 kyu

#169 Closes #152 Looking for a benefactor
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/SevenImpl.java
Labels: 7 kyu

#168 Closes #151 Find numbers which are divisible by given number
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/EightImpl.java
Labels: 8 kyu

#167 Closes #150 Formatting decimal places
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/EightImpl.java
Labels: 8 kyu

#166 Closes #149 Willson primes
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/EightImpl.java
Labels: 8 kyu

#165 Bookseller
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/Six.java
Labels: 6 kyu

#164 Closes #118 Convert a String to a Number!
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/EightImpl.java
Labels: 8 kyu

#163 Closes #117 Count of positives / sum of negatives
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/EightImpl.java
Labels: 8 kyu

#162 Closes #116 To square root or no to square
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/EightImpl.java
Labels: 8 kyu

#161 Closes #115 Miles per gallon to kilometers per liter
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/EightImpl.java
Labels: 8 kyu

#160 Closes #114 Get volume of cuboid
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/EightImpl.java
Labels: 8 kyu

#159 Closes #113 Keep Hydrated!
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/EightImpl.java
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/SixImpl.java
Labels: 8 kyu

#158 Kostyra/perimeter-of-squares
  src/main/java/com/ss/ita/kata/implementation/Percifalll/FiveImpl.java
Labels: 5 kyu

#157 Kostyra/trailing-zeros
  src/main/java/com/ss/ita/kata/implementation/Percifalll/FiveImpl.java
Labels: 5 kyu

#156 Kostyra/prime-gap
  src/main/java/com/ss/ita/kata/implementation/Percifalll/FiveImpl.java
Labels: 5 kyu

#155 Kostyra/help-a-bookseller
  src/main/java/com/ss/ita/kata/implementation/Percifalll/SixImpl.java
Labels: 6 kyu

#148 V dmytriv trailing
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/FiveImpl.java
Labels: 5 kyu

#145 complete task Trailing zeros in factorial
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/FiveImpl.java
Labels: 5 kyu

#142 complete task Build a pile of Cubes
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/SixImpl.java
Labels: 6 kyu

#138 Looking for a benefactor
  src/main/java/com/ss/ita/kata/implementation/NyxLex/SevenImpl.java
Labels: 7 kyu

#137 Sum of the first nth term of Series
  src/main/java/com/ss/ita/kata/implementation/NyxLex/SevenImpl.java
Labels: 7 kyu

#136 Where is Vasya?
  src/main/java/com/ss/ita/kata/implementation/NyxLex/SevenImpl.java
Labels: 7 kyu

#135 Vdmytriv wilson
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/EightImpl.java
Labels: 8 kyu

#134 complete task WhereIsVasya
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/SevenImpl.java
Labels: 7 kyu

#132 Wilson primes
  src/main/java/com/ss/ita/kata/implementation/NyxLex/EightImpl.java
Labels: 8 kyu

#131 Find numbers which are divisible by given number
  src/main/java/com/ss/ita/kata/implementation/NyxLex/EightImpl.java
Labels: 8 kyu

#130 Formatting decimal places
  src/main/java/com/ss/ita/kata/implementation/NyxLex/EightImpl.java
Labels: 8 kyu

#129 stringToNumber
  src/main/java/com/ss/ita/kata/implementation/NyxLex/EightImpl.java
Labels: 8 kyu

#128 Count of positives / sum of negatives
  src/main/java/com/ss/ita/kata/implementation/NyxLex/EightImpl.java
Labels: 8 kyu

#127 To square root or no to square
  src/main/java/com/ss/ita/kata/implementation/NyxLex/EightImpl.java
Labels: 8 kyu

#126 Miles per gallon to kilometers per liter
  src/main/java/com/ss/ita/kata/implementation/NyxLex/EightImpl.java
Labels: 8 kyu

#125 complete task seriusSam
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/SevenImpl.java
Labels: 7 kyu

#123 Volume of a cuboid
  src/main/java/com/ss/ita/kata/implementation/NyxLex/EightImpl.java
Labels: 8 kyu

#121 Keep Hydrated!
  src/main/java/com/ss/ita/kata/implementation/NyxLex/EightImpl.java
Labels: 8 kyu

#120 complete task lokking for a benefactor
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/SevenImpl.java
Labels: 7 kyu

#106 V dmytriv build
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/Six.java
Labels: 6 kyu

#101 Kostyra/where-is-vasya
  src/main/java/com/ss/ita/kata/implementation/Percifalll/SevenImpl.java
Labels: 7 kyu

#93 Kostyra/sum-of-first-nth-series
  src/main/java/com/ss/ita/kata/implementation/Percifalll/SevenImpl.java
Labels: 7 kyu

#82 complete task divisibleBy with good solution
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/EightImpl.java
Labels: 8 kyu

#81 Kostyra/looking-for-a-benefactor
  src/main/java/com/ss/ita/kata/implementation/Percifalll/SevenImpl.java
Labels: 7 kyu

#80 Kostyra/find-numbers-which-are-divisible
  src/main/java/com/ss/ita/kata/implementation/Percifalll/EightImpl.java
Labels: 8 kyu

#79 Kostyra/formatting-decimal-places
  src/main/java/com/ss/ita/kata/implementation/Percifalll/EightImpl.java
Labels: 8 kyu

#71 Where is Vasya?
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/SevenImpl.java
Labels: 7 kyu

#57 DivisibleBy
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/EightImpl.java
Labels: 8 kyu

#74 #72 am i wilson
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/EightImpl.java
Labels: 8 kyu

#78 Kostyra/am-i-wilson
  src/main/java/com/ss/ita/kata/implementation/Percifalll/EightImpl.java
Labels: 8 kyu

#111 Kostyra/build-a-pile-of-cubes
  src/main/java/com/ss/ita/kata/implementation/Percifalll/SixImpl.java
Labels: 6 kyu

#139 Kostyra/easy-balance
  src/main/java/com/ss/ita/kata/implementation/Percifalll/SixImpl.java
Labels: 6 kyu

#143 Kostyra/rainfall
  src/main/java/com/ss/ita/kata/implementation/Percifalll/SixImpl.java
Labels: 6 kyu

#147 Kostyra/nba
  src/main/java/com/ss/ita/kata/implementation/Percifalll/SixImpl.java
Labels: 6 kyu

#95 Dzhyv/keep hydrated
  .gitignore
  src/main/java/com/ss/ita/kata/implementation/dzhyv/EightImpl.java
  src/main/java/com/ss/ita/kata/implementation/dzhyv/Siximpl.java
Labels: 8 kyu

#96 Dzhyv/find numbers which are divisible by given number
  .gitignore
  src/main/java/com/ss/ita/kata/implementation/dzhyv/EightImpl.java
  src/main/java/com/ss/ita/kata/implementation/dzhyv/Siximpl.java
Labels: 8 kyu

#97 Dzhyv/to square(root)) or not to square(root)
  src/main/java/com/ss/ita/kata/implementation/dzhyv/EightImpl.java
  src/main/java/com/ss/ita/kata/implementation/dzhyv/Siximpl.java
Labels: 8 kyu

#98 Dzhyv/convert a string to a number
  src/main/java/com/ss/ita/kata/implementation/dzhyv/EightImpl.java
  src/main/java/com/ss/ita/kata/implementation/dzhyv/Siximpl.java
Labels: 8 kyu

#99 Dzhyv/count of postives sum of negatives
  src/main/java/com/ss/ita/kata/implementation/dzhyv/EightImpl.java
Labels: 8 kyu

#102 Dzhyv/miles per gallon to killometers per liter
  src/main/java/com/ss/ita/kata/implementation/dzhyv/EightImpl.java
Labels: 8 kyu

#103 Dzhyv/wilson primes
  src/main/java/com/ss/ita/kata/implementation/dzhyv/EightImpl.java
Labels: 8 kyu

#104 Dzhyv/volume of a cuboid
  src/main/java/com/ss/ita/kata/implementation/dzhyv/EightImpl.java
Labels: 8 kyu

#107 Dzhyv/looking for a benefactor
  .gitignore
  src/main/java/com/ss/ita/kata/implementation/dzhyv/SevenImpl.java
Labels: 7 kyu

#109 Dzhyv/sum of the first nth term of series
  .gitignore
  src/main/java/com/ss/ita/kata/implementation/dzhyv/SevenImpl.java
Labels: 7 kyu

#140 easyBalance
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/Six.java
Labels: 6 kyu

#146 V dmytriv rainfall
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/Six.java
Labels: 6 kyu

#174 Dzhyv/gap in primes
  src/main/java/com/ss/ita/kata/implementation/dzhyv/FiveImpl.java
Labels: 5 kyu

#245 completed task easy check balance
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/SixImpl.java
Labels: 6 kyu

#240 Implemented Artificial rain
  src/main/java/com/ss/ita/kata/implementation/dzhyv/FiveImpl.java
Labels: 5 kyu

#243 V dmytriv nba
  src/main/java/com/ss/ita/kata/implementation/vladdmytriv/SixImpl.java
Labels: 6 kyu

#247 SixImpl
  src/main/java/com/ss/ita/kata/implementation/NyxLex/SixImpl.java
Labels: 6 kyu

#249 Implemented Find the smallest
  src/main/java/com/ss/ita/kata/implementation/dzhyv/FiveImpl.java
Labels: 5 kyu

#252 completed task Ranking NBA
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/SixImpl.java
Labels: 6 kyu

#254 Kostyra/artificial rain
  src/main/java/com/ss/ita/kata/implementation/Percifalll/FiveImpl.java
Labels: 5 kyu

#265 completed task Rainfall
  src/main/java/com/ss/ita/kata/implementation/NazarYakh/SixImpl.java
Labels: 6 kyu

#263 Nba cup + rename Siximpl to SixImpl
  src/main/java/com/ss/ita/kata/implementation/dzhyv/SixImpl.java
  src/main/java/com/ss/ita/kata/implementation/dzhyv/Siximpl.java
Labels: 6 kyu

#276 Closes #270 Build a pile of Cubes
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/SixImpl.java
Labels: 6 kyu

#277 Closes #271 Easy balance checking
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/SixImpl.java
Labels: 6 kyu

#278 Closes #272 Floating-point Approximation (I)
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/SixImpl.java
Labels: 6 kyu

#279 Closes #273 Rainfall
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/SixImpl.java
Labels: 6 kyu

#281 Closes #275 Help the bookseller!
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/SixImpl.java
Labels: 6 kyu

#285 Closes #282 Artificial Rain
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/FiveImpl.java
Labels: 5 kyu

#286 Closes #283 Gap in Primes
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/FiveImpl.java
Labels: 5 kyu

#287 Closes #284 Find the smallest
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/FiveImpl.java
Labels: 5 kyu

#280 Closes #274 Ranking NBA
  src/main/java/com/ss/ita/kata/implementation/anastasia8755/SixImpl.java
Labels: 6 kyu

#295 Formatting decimal places #0
  src/main/java/com/ss/ita/kata/implementation/VladGranat/EightImpl.java
Labels: 8 kyu

#299 Find numbers which are divisible by given number
  src/main/java/com/ss/ita/kata/implementation/VladGranat/EightImpl.java
Labels: 8 kyu
